services:
  postgres:
    image: postgres:18-alpine
    container_name: ims-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./code/jvm/repository-jdbi/src/sql/create-schema.sql:/docker-entrypoint-initdb.d/1_create.sql
      - ./code/jvm/repository-jdbi/src/sql/insert-test-data.sql:/docker-entrypoint-initdb.d/2_data.sql
    ports:
      - "5432:5432"
    networks:
      - ims-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: ims-redis
    ports:
      - "6379:6379"
    networks:
      - ims-network

  backend:
    build:
      context: ./code/jvm
      dockerfile: Dockerfile
    container_name: ims-backend
    environment:
      DB_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_DATA_REDIS_HOST: redis
      CORS_ALLOWED_ORIGINS: "http://localhost:8000,http://192.168.1.120:8000"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - ims-network

  frontend:
    build:
      context: ./code/js
      dockerfile: Dockerfile
    container_name: ims-frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - ims-network

volumes:
  postgres_data:
    name: postgres_data

networks:
  ims-network:
    name: ims-network
    driver: bridge