[versions]
kotlin = "2.2.21"
spring-boot = "3.5.11"
ktlint = "14.0.1"
jdbi = "3.51.0"
jjwt = "0.13.0"

[libraries]
# Jakarta
jakarta-inject-api = { group = "jakarta.inject", name = "jakarta.inject-api" }

# Spring Boot
spring-boot-dependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter-jdbc = { group = "org.springframework.boot", name = "spring-boot-starter-jdbc" }
spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
spring-boot-starter-webflux = { group = "org.springframework.boot", name = "spring-boot-starter-webflux" }
spring-boot-starter-data-redis = { group = "org.springframework.boot", name = "spring-boot-starter-data-redis" }

# Spring Security
spring-security-core = { group = "org.springframework.security", name = "spring-security-core" }

# Kotlin & Utilities
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect" }
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin" }

# Database
postgresql = { group = "org.postgresql", name = "postgresql" }

# JDBI
jdbi3-core = { group = "org.jdbi", name = "jdbi3-core", version.ref = "jdbi" }
jdbi3-kotlin = { group = "org.jdbi", name = "jdbi3-kotlin", version.ref = "jdbi" }
jdbi3-postgres = { group = "org.jdbi", name = "jdbi3-postgres", version.ref = "jdbi" }

# Security / JWT
jjwt-api = { group = "io.jsonwebtoken", name = "jjwt-api", version.ref = "jjwt"}
jjwt-impl = { group = "io.jsonwebtoken", name = "jjwt-impl", version.ref = "jjwt"}
jjwt-jackson = { group = "io.jsonwebtoken", name = "jjwt-jackson", version.ref = "jjwt"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
